### ISSUE TITLE
The agents not moving

### ISSUE THREAD

**Issue by syahmi001** [hanruihua/rvo_ros#1]
Hello and Hi

I am interested in your coding and wanted to use them in real robot navigation.
I tested them in ROS Kinetic with ubuntu 16.04. The codes compiled successfully but when I run the services,
the agents are not moving. They are only standing still forming a straight line.

I followed exactly your instruction, or did I missing something?

**Comment by hanruihua** [comment]
Hi, thanks for your attention. 

First, each agent receives the velocity from the ros topic by a plugin located in the folder simulation/plugins. Thus, you should check whether the file  _world_multi_obs.cc_ is compiled successfully. 

Second, if the file _world_multi_obs.cc_ is compiled successfully,  you should check the environment parameter GAZEBO_PLUGIN_PATH which is the path of the gazebo plugin (using echo $GAZEBO_PLUGIN_PATH). It should be set in the shell (bash or zsh ) and includes the path of plugins compiled in the previous step. The path is commonly ~/catkin_ws/devel/lib.     

Actually, this code is also tested in ROS Kinetic with ubuntu 16.04 and it works well. However, in ubuntu 16.04, there may be a problem with the protoc version. The default version is 3.4, but for the gazebo, it should be protoc 2.6.1.

**Comment by syahmi001** [comment]
Oh thanks for the swift reply!

Never thought my message would be replied this quickly.
I have taken your advice and now it works wonderfully well!!!

My mistake was I forgot to write:
`export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:~/catkin_ws/devel/lib`
in my bashrc file.

Once I export them, they work pretty well.
Thanks again!!! :)
